# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
#  - release
#  - devel
sudo: false
warnings_are_errors: false
cache: packages

addons:
  apt:
    packages:
      - libgit2-dev

install:
  - Rscript -e 'install.packages("devtools", version = "1.9.1", repos = "http://cran.rstudio.com")'

r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'
