# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
cache: packages

addons:
  apt:
    packages:
      - libgit2-dev

r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'
