# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
cache: packages

addons:
  apt:
    packages:
      - libgit2-dev

# adding ncdf4 or libgit2 via binary packages does not work 
# r_binary_packages:
#   - ncdf4

## Use patched devtools
r_github_packages:
  - hadley/devtools
  
r_packages:
  - covr

after_success:
- Rscript -e 'covr::codecov()'
